server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://43.138.15.180:3306/mine?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: canal
    username: CANALcc654321!
